# -*- coding: utf-8 -*-
"""mllll.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TRl8eeluFjVxitxsJaIi50gB-JWc3e2f
"""

# ============================================================
# DR Grading — 3-Class Final (v5)
# HOW TO VERIFY THIS IS THE RIGHT FILE:
#   - Search for "STAGE 2" → should NOT exist anywhere
#   - Search for "cosine" → should appear in LR schedule
#   - Search for "MixUp" → should appear in training section
# ============================================================

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

import pandas as pd
import numpy as np
import os, cv2, shutil
import matplotlib.pyplot as plt
import seaborn as sns
import tensorflow as tf

from sklearn.model_selection import train_test_split
from sklearn.metrics import (confusion_matrix, classification_report,
                              roc_curve, auc, cohen_kappa_score)
from sklearn.preprocessing import label_binarize
from sklearn.utils.class_weight import compute_class_weight
from tensorflow.keras.applications import EfficientNetB0
from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras.layers import (Dense, GlobalAveragePooling2D,
                                      Dropout, BatchNormalization)
from tensorflow.keras.models import Model
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

# ─────────────────────────────────────────────────────────────
# CONFIG
# ─────────────────────────────────────────────────────────────
BASE_PATH        = '/content/drive/MyDrive/ML PROJECT DATASET/MLproject/B. Disease Grading'
GROUNDTRUTH_PATH = BASE_PATH + '/2. Groundtruths'
TRAIN_DIR        = BASE_PATH + '/1. Original Images/a. Training Set'
TEST_DIR         = BASE_PATH + '/1. Original Images/b. Testing Set'
SAVE_DIR         = '/content/drive/MyDrive/ML PROJECT DATASET/MLproject'

IMG_SIZE     = 224
BATCH_SIZE   = 16
NUM_CLASSES  = 3
TOTAL_EPOCHS = 30
WARMUP_EPOCHS = 3
BASE_LR      = 1e-3
MIN_LR       = 1e-6

LABEL_MAP = {0: "No/Mild DR", 1: "Moderate DR", 2: "Severe/Prolif. DR"}
GRADE_TO_CLASS = {0: 0, 1: 0, 2: 1, 3: 2, 4: 2}

print("=" * 50)
print("DR GRADING v5 — SINGLE STAGE + MIXUP + COSINE LR")
print("=" * 50)

# ─────────────────────────────────────────────────────────────
# 1. CLEAR OLD CACHE + LOAD DATA
# ─────────────────────────────────────────────────────────────
for d in ['/content/prep_train', '/content/prep_test']:
    if os.path.exists(d):
        shutil.rmtree(d)
os.makedirs('/content/prep_train', exist_ok=True)
os.makedirs('/content/prep_test',  exist_ok=True)

train_df = pd.read_csv(GROUNDTRUTH_PATH + '/a. IDRiD_Disease Grading_Training Labels.csv')
test_df  = pd.read_csv(GROUNDTRUTH_PATH + '/b. IDRiD_Disease Grading_Testing Labels.csv')

train_df = train_df[['Image name', 'Retinopathy grade']].dropna()
test_df  = test_df[['Image name',  'Retinopathy grade']].dropna()

train_df['class3'] = train_df['Retinopathy grade'].astype(int).map(GRADE_TO_CLASS).astype(str)
test_df['class3']  = test_df['Retinopathy grade'].astype(int).map(GRADE_TO_CLASS).astype(str)
train_df['path']   = train_df['Image name'].apply(lambda x: os.path.join(TRAIN_DIR, x.strip() + '.jpg'))
test_df['path']    = test_df['Image name'].apply(lambda x: os.path.join(TEST_DIR,  x.strip() + '.jpg'))

print("\n3-CLASS DISTRIBUTION")
print("Train:", dict(train_df['class3'].value_counts().sort_index()))
print("Test: ", dict(test_df['class3'].value_counts().sort_index()))

# ─────────────────────────────────────────────────────────────
# 2. CLAHE PREPROCESSING — saved as uint8, NO /255
#    EfficientNetB0 has its own internal Rescaling layer.
#    Feeding [0,255] uint8 is correct.
# ─────────────────────────────────────────────────────────────
def apply_clahe_and_save(src_path, dst_dir):
    fname    = os.path.splitext(os.path.basename(src_path))[0] + '.png'
    dst_path = os.path.join(dst_dir, fname)
    img = cv2.imread(src_path)
    if img is None:
        cv2.imwrite(dst_path, np.zeros((IMG_SIZE, IMG_SIZE, 3), dtype=np.uint8))
        return dst_path
    img  = cv2.resize(img, (IMG_SIZE, IMG_SIZE))
    lab  = cv2.cvtColor(img, cv2.COLOR_BGR2LAB)
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
    lab[:, :, 0] = clahe.apply(lab[:, :, 0])
    img  = cv2.cvtColor(lab, cv2.COLOR_LAB2BGR)
    cv2.imwrite(dst_path, img)
    return dst_path

print("\nApplying CLAHE (fresh cache)...")
train_df['prep_path'] = train_df['path'].apply(lambda p: apply_clahe_and_save(p, '/content/prep_train'))
test_df['prep_path']  = test_df['path'].apply(lambda p: apply_clahe_and_save(p, '/content/prep_test'))
print("Done.")

# ─────────────────────────────────────────────────────────────
# 3. TRAIN / VAL SPLIT
# ─────────────────────────────────────────────────────────────
train_split_df, val_df = train_test_split(
    train_df, test_size=0.2, random_state=42, stratify=train_df['class3'])
train_split_df = train_split_df.reset_index(drop=True)
val_df         = val_df.reset_index(drop=True)
test_df        = test_df.reset_index(drop=True)
print(f"\nSplit → Train: {len(train_split_df)} | Val: {len(val_df)} | Test: {len(test_df)}")

# ─────────────────────────────────────────────────────────────
# 4. CLASS WEIGHTS — Moderate gets extra 1.8x boost
#    In v4: Moderate (class 1) had F1=0.38, 15/32 misclassified
# ─────────────────────────────────────────────────────────────
grades_int = train_split_df['class3'].astype(int).values
raw_w      = compute_class_weight('balanced', classes=np.arange(NUM_CLASSES), y=grades_int)
class_weights = {i: min(float(w), 4.0) for i, w in enumerate(raw_w)}
class_weights[1] = min(class_weights[1] * 1.8, 5.0)  # Moderate boost

print("\nClass weights:")
for k, v in class_weights.items():
    print(f"  {LABEL_MAP[k]}: {v:.3f}")

# ─────────────────────────────────────────────────────────────
# 5. MIXUP GENERATOR
#    Blends pairs of images+labels to reduce overfitting
#    and improve calibration on small datasets.
# ─────────────────────────────────────────────────────────────
def mixup_generator(generator, alpha=0.3):
    while True:
        X1, y1 = next(generator)
        X2, y2 = next(generator)
        n   = min(len(X1), len(X2))
        X1, y1, X2, y2 = X1[:n], y1[:n], X2[:n], y2[:n]
        lam = np.random.beta(alpha, alpha, size=(n, 1, 1, 1)).astype(np.float32)
        X_mix = lam * X1 + (1 - lam) * X2
        y_mix = lam.reshape(n, 1) * y1 + (1 - lam.reshape(n, 1)) * y2
        yield X_mix, y_mix

# ─────────────────────────────────────────────────────────────
# 6. DATA GENERATORS — NO rescale (EfficientNet handles it)
# ─────────────────────────────────────────────────────────────
train_datagen = ImageDataGenerator(
    rotation_range=25,
    width_shift_range=0.10,
    height_shift_range=0.10,
    zoom_range=0.15,
    horizontal_flip=True,
    vertical_flip=True,
    brightness_range=[0.80, 1.20],
    shear_range=0.1,
    fill_mode='nearest'
)
eval_datagen = ImageDataGenerator()

def make_gen(datagen, df, shuffle):
    return datagen.flow_from_dataframe(
        dataframe=df, x_col='prep_path', y_col='class3',
        target_size=(IMG_SIZE, IMG_SIZE), color_mode='rgb',
        class_mode='categorical', batch_size=BATCH_SIZE,
        shuffle=shuffle, validate_filenames=False)

train_gen_raw  = make_gen(train_datagen, train_split_df, shuffle=True)
train_gen_mix  = make_gen(train_datagen, train_split_df, shuffle=True)
train_gen_mixup = mixup_generator(train_gen_mix, alpha=0.3)

val_gen  = make_gen(eval_datagen, val_df,  shuffle=False)
test_gen = make_gen(eval_datagen, test_df, shuffle=False)

steps_per_epoch = len(train_split_df) // BATCH_SIZE
print(f"\nSteps per epoch: {steps_per_epoch}")

# ─────────────────────────────────────────────────────────────
# 7. COSINE ANNEALING LR — smooth decay, no premature collapse
#    v4 used ReduceLROnPlateau which dropped LR too early
# ─────────────────────────────────────────────────────────────
def cosine_lr(epoch):
    if epoch < WARMUP_EPOCHS:
        return BASE_LR * (epoch + 1) / WARMUP_EPOCHS
    progress = (epoch - WARMUP_EPOCHS) / (TOTAL_EPOCHS - WARMUP_EPOCHS)
    return MIN_LR + 0.5 * (BASE_LR - MIN_LR) * (1 + np.cos(np.pi * progress))

lr_scheduler = tf.keras.callbacks.LearningRateScheduler(cosine_lr, verbose=0)

# ─────────────────────────────────────────────────────────────
# 8. BUILD MODEL
# ─────────────────────────────────────────────────────────────
base = EfficientNetB0(weights='imagenet', include_top=False,
                      input_shape=(IMG_SIZE, IMG_SIZE, 3))
base.trainable = False

x   = base.output
x   = GlobalAveragePooling2D()(x)
x   = BatchNormalization()(x)
x   = Dense(256, activation='relu',
            kernel_regularizer=tf.keras.regularizers.l2(1e-4))(x)
x   = Dropout(0.45)(x)
x   = Dense(128, activation='relu',
            kernel_regularizer=tf.keras.regularizers.l2(1e-4))(x)
x   = Dropout(0.35)(x)
out = Dense(NUM_CLASSES, activation='softmax')(x)
model = Model(inputs=base.input, outputs=out)

model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=BASE_LR),
    loss=tf.keras.losses.CategoricalCrossentropy(label_smoothing=0.1),
    metrics=['accuracy']
)

total_params     = model.count_params()
trainable_params = sum(tf.size(w).numpy() for w in model.trainable_weights)
print(f"\nModel: {total_params:,} total params | {trainable_params:,} trainable")

# ─────────────────────────────────────────────────────────────
# 9. TRAIN — SINGLE STAGE ONLY (no Stage 2)
#    v4 showed Stage 2 dropped val_acc from 80% → 72%
#    Extended training + cosine LR extracts more from frozen base
# ─────────────────────────────────────────────────────────────
ckpt_path = os.path.join(SAVE_DIR, 'dr_v5_best.keras')

callbacks = [
    EarlyStopping(monitor='val_accuracy', patience=9,
                  restore_best_weights=True, verbose=1, mode='max'),
    ModelCheckpoint(ckpt_path, monitor='val_accuracy',
                    save_best_only=True, verbose=1, mode='max'),
    lr_scheduler
]

print("\n=== SINGLE-STAGE TRAINING (MixUp + cosine LR, max 30 epochs) ===")
print("Look for: NO 'STAGE 2' — NO 'ReduceLROnPlateau' messages\n")

history = model.fit(
    train_gen_mixup,
    steps_per_epoch=steps_per_epoch,
    validation_data=val_gen,
    epochs=TOTAL_EPOCHS,
    # Removed class_weight as it's not supported with Python generators like mixup_generator
    # For class weighting with custom generators, weights need to be incorporated directly into the generator's output
    # or the loss function.
    callbacks=callbacks
)

best_val_acc = max(history.history['val_accuracy'])
print(f"\nBest val accuracy across all epochs: {best_val_acc:.4f}")

# ─────────────────────────────────────────────────────────────
# 10. TEST EVALUATION — STANDARD
# ─────────────────────────────────────────────────────────────
test_gen_eval = make_gen(eval_datagen, test_df, shuffle=False)
test_gen_eval.reset()
loss_val, acc_std = model.evaluate(test_gen_eval, verbose=1)

test_gen_eval.reset()
preds_std = model.predict(test_gen_eval, verbose=1)
pred_std  = np.argmax(preds_std, axis=1)
true_cls  = test_gen_eval.classes

print(f"\nStandard — Accuracy: {acc_std*100:.2f}%  QWK: {cohen_kappa_score(true_cls, pred_std, weights='quadratic'):.4f}")
print(f"True dist    : {np.bincount(true_cls)}")
print(f"Pred dist    : {np.bincount(pred_std)}")

# ─────────────────────────────────────────────────────────────
# 11. TEST-TIME AUGMENTATION — 8 passes
#     Averages predictions across augmented versions → more robust
# ─────────────────────────────────────────────────────────────
tta_datagen = ImageDataGenerator(
    rotation_range=15, horizontal_flip=True,
    zoom_range=0.08, brightness_range=[0.9, 1.1], fill_mode='nearest'
)

def predict_tta(model, df, n_aug=8):
    all_preds = []
    print(f"\nRunning TTA ({n_aug} passes):")
    for i in range(n_aug):
        print(f"  Pass {i+1}/{n_aug}...", end='\r')
        g = tta_datagen.flow_from_dataframe(
            dataframe=df, x_col='prep_path', y_col='class3',
            target_size=(IMG_SIZE, IMG_SIZE), color_mode='rgb',
            class_mode='categorical', batch_size=BATCH_SIZE,
            shuffle=False, validate_filenames=False)
        all_preds.append(model.predict(g, verbose=0))
    print("\nTTA complete.")
    return np.mean(all_preds, axis=0)

preds_tta = predict_tta(model, test_df, n_aug=8)
pred_tta  = np.argmax(preds_tta, axis=1)

qwk_std = cohen_kappa_score(true_cls, pred_std, weights='quadratic')
qwk_tta = cohen_kappa_score(true_cls, pred_tta, weights='quadratic')
acc_tta = float(np.mean(true_cls == pred_tta))

print(f"\nTTA     — Accuracy: {acc_tta*100:.2f}%  QWK: {qwk_tta:.4f}")
print(f"Pred dist (TTA): {np.bincount(pred_tta)}")

# ─────────────────────────────────────────────────────────────
# 12. DETAILED REPORTS
# ─────────────────────────────────────────────────────────────
label_names = list(LABEL_MAP.values())
cm_std = confusion_matrix(true_cls, pred_std)
cm_tta = confusion_matrix(true_cls, pred_tta)

print("\n--- STANDARD PREDICTIONS ---")
print("Confusion Matrix:\n", cm_std)
print(classification_report(true_cls, pred_std,
      target_names=label_names, zero_division=0))

print("\n--- TTA PREDICTIONS ---")
print("Confusion Matrix:\n", cm_tta)
print(classification_report(true_cls, pred_tta,
      target_names=label_names, zero_division=0))

# ─────────────────────────────────────────────────────────────
# 13. PLOTS
# ─────────────────────────────────────────────────────────────
# LR schedule
lrs = [cosine_lr(e) for e in range(TOTAL_EPOCHS)]
actual_epochs = len(history.history['accuracy'])

fig, axes = plt.subplots(1, 3, figsize=(18, 5))

axes[0].plot(history.history['accuracy'],     label='Train', color='steelblue')
axes[0].plot(history.history['val_accuracy'], label='Val',   color='tomato')
axes[0].set_title('Accuracy — single stage'); axes[0].set_xlabel('Epoch')
axes[0].set_ylabel('Accuracy'); axes[0].legend()
axes[0].set_ylim(0, 1)

axes[1].plot(history.history['loss'],     label='Train', color='steelblue')
axes[1].plot(history.history['val_loss'], label='Val',   color='tomato')
axes[1].set_title('Loss — single stage'); axes[1].set_xlabel('Epoch')
axes[1].set_ylabel('Loss'); axes[1].legend()

axes[2].plot(lrs[:actual_epochs], color='darkorange')
axes[2].set_title('Cosine annealing LR')
axes[2].set_xlabel('Epoch'); axes[2].set_ylabel('LR')
axes[2].set_yscale('log')
plt.tight_layout()
plt.savefig(os.path.join(SAVE_DIR, 'curves_v5.png'), dpi=150)
plt.show()

# Confusion matrices side by side
fig, axes = plt.subplots(1, 2, figsize=(14, 5))
for ax, cm_d, tag, acc_v, qwk_v in [
    (axes[0], cm_std, 'Standard', acc_std, qwk_std),
    (axes[1], cm_tta, 'TTA (8 passes)', acc_tta, qwk_tta)
]:
    sns.heatmap(cm_d, annot=True, fmt='d', cmap='Blues',
                xticklabels=label_names, yticklabels=label_names, ax=ax)
    ax.set_title(f'{tag}  Acc={acc_v*100:.1f}%  QWK={qwk_v:.3f}')
    ax.set_ylabel('True'); ax.set_xlabel('Predicted')
plt.tight_layout()
plt.savefig(os.path.join(SAVE_DIR, 'cm_v5.png'), dpi=150)
plt.show()

# ROC curves
y_bin = label_binarize(true_cls, classes=[0, 1, 2])
plt.figure(figsize=(7, 6))
for i, (name, color) in enumerate(zip(
    label_names, ['steelblue', 'seagreen', 'tomato'])):
    fpr, tpr, _ = roc_curve(y_bin[:, i], preds_tta[:, i])
    plt.plot(fpr, tpr, color=color, lw=2,
             label=f'{name} AUC={auc(fpr, tpr):.2f}')
plt.plot([0,1],[0,1],'k--',lw=1)
plt.xlabel('FPR'); plt.ylabel('TPR')
plt.title('ROC (TTA, one-vs-rest)'); plt.legend(loc='lower right')
plt.tight_layout()
plt.savefig(os.path.join(SAVE_DIR, 'roc_v5.png'), dpi=150)
plt.show()

# Per-class confidence histograms
fig, axes = plt.subplots(1, 3, figsize=(15, 4))
for i, (name, color) in enumerate(zip(
    label_names, ['steelblue', 'seagreen', 'tomato'])):
    mask  = true_cls == i
    probs = preds_tta[mask, i]
    correct = pred_tta[mask] == i
#     axes[i].hist(probs[correct],  bins=10, alpha=0.7, color='green',  label='Correct')
#     axes[i].hist(probs[~correct], bins=10, alpha=0.7, color='red',    label='Wrong')
#     axes[i].set_title(f'{name}')
#     axes[i].set_xlabel('Confidence'); axes[i].set_ylabel('Count')
#     axes[i].legend()
# plt.suptitle('Per-class prediction confidence (TTA)')
# plt.tight_layout()
# plt.savefig(os.path.join(SAVE_DIR, 'confidence_v5.png'), dpi=150)
# plt.show()

# ─────────────────────────────────────────────────────────────
# 14. SINGLE IMAGE PREDICTION
# ─────────────────────────────────────────────────────────────
def predict_single(img_path, use_tta=True):
    if not os.path.exists(img_path):
        print(f"Not found: {img_path}"); return
    img_bgr = cv2.imread(img_path)
    img_bgr = cv2.resize(img_bgr, (IMG_SIZE, IMG_SIZE))
    lab = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2LAB)
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
    lab[:, :, 0] = clahe.apply(lab[:, :, 0])
    img_bgr = cv2.cvtColor(lab, cv2.COLOR_LAB2BGR)
    img_rgb = cv2.cvtColor(img_bgr, cv2.COLOR_BGR2RGB)
    batch   = np.expand_dims(img_rgb.astype(np.float32), 0)

    if use_tta:
        all_p = [model.predict(next(tta_datagen.flow(batch, batch_size=1)), verbose=0)[0]
                 for _ in range(8)]
        probs = np.mean(all_p, axis=0)
    else:
        probs = model.predict(batch, verbose=0)[0]

    pred = int(np.argmax(probs))
    print(f"\n  Class     : {pred} — {LABEL_MAP[pred]}")
    print(f"  Confidence: {probs[pred]*100:.1f}%")
    print("  All probs :", {LABEL_MAP[i]: f"{p*100:.1f}%" for i,p in enumerate(probs)})
    plt.figure(figsize=(5,5)); plt.imshow(img_rgb)
    plt.title(f"{LABEL_MAP[pred]} ({probs[pred]*100:.1f}%)"); plt.axis('off'); plt.show()

print("\nSample prediction:")
predict_single(test_df['path'].iloc[0])

# ─────────────────────────────────────────────────────────────
# 15. SAVE MODEL
# ─────────────────────────────────────────────────────────────
final_path = os.path.join(SAVE_DIR, 'dr_v5_final.keras')
model.save(final_path)
print(f"\nModel saved: {final_path}")

# ─────────────────────────────────────────────────────────────
# FINAL SUMMARY
# ─────────────────────────────────────────────────────────────
report = classification_report(true_cls, pred_tta, output_dict=True,
                                target_names=label_names, zero_division=0)
print("\n" + "=" * 60)
print("FINAL SUMMARY  —  v5  (compare to v4 in brackets)")
print("=" * 60)
print(f"  Accuracy  (TTA)  : {acc_tta*100:.2f}%   [was 61.17%]")
print(f"  QWK       (TTA)  : {qwk_tta:.4f}   [was 0.5896]")
print(f"  Accuracy  (std)  : {acc_std*100:.2f}%")
print(f"  QWK       (std)  : {qwk_std:.4f}")
print("-" * 60)
for name in label_names:
    r = report[name]
    prev = {"No/Mild DR": "0.73", "Moderate DR": "0.38", "Severe/Prolif. DR": "0.63"}
    print(f"  {name:<22}  F1={r['f1-score']:.2f}  "
          f"P={r['precision']:.2f}  R={r['recall']:.2f}"
          f"   [F1 was {prev[name]}]")
print("=" * 60)
print("\nClass mapping:")
for orig, new in GRADE_TO_CLASS.items():
    print(f"  Grade {orig} → Class {new} ({LABEL_MAP[new]})")

sample_image_path = '/content/IDRiD_092.jpg'
print(f"Predicting for image: {sample_image_path}")
predict_single(sample_image_path, use_tta=True)